### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by luiarthur** [luiarthur/boggle-react-ts#1]
- [ ] Redo this project in Typescript + React with the following improvements
    - [x] Provide a board
    - [x] Provide solutions
    - [x] Allow entering a rng seed
    - [ ] Play with other users using Firebase authentication
    - [ ] Allow users to enter their solution (using finger swipes)
    - [ ] Compute scores (with press of button) after time is up
    - [ ] Optionally show number of possible words on screen before playing
    - [ ] Add a timer
    - [ ] Allow custom dictionary submissions
    - [x] Use GitHub actions to build and add to gh-page branch when tagged
